name: Debug Logging Demo

on: push

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Call 
          run: curl --location 'https://httpbin.org/basic-auth/foo/bar' 