name: Debug Logging Demo

on: push

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Call 
          run: |
            curl -s "https://httpbin.org/basic-auth/foo/bar" --header "Authorization: Basic Zm9vOmJhcg=="
            jq version
            exit 1